## Implementacion de One Hot Enconding en un data set relacionado a Recursos Humanos

In [4]:
#Importar las librerias
import pandas as pd
import numpy as np

In [8]:
df_rh = pd.read_csv("HRDataset_v14.csv")

In [10]:
df_rh.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [16]:
df_rh1 = df_rh[["Employee_Name","Position","State","Sex","DOB","MaritalDesc",
               "CitizenDesc","Department","PerformanceScore","EngagementSurvey","EmpSatisfaction"]]

In [18]:
df_rh1.shape

(311, 11)

In [20]:
df_rh1.head()

,Employee_Name,Position,State,Sex,DOB,MaritalDesc,CitizenDesc,Department,PerformanceScore,EngagementSurvey,EmpSatisfaction
0,"Adinolfi, Wilson K",Production Technician I,MA,M,07/10/83,Single,US Citizen,Production,Exceeds,4.60,5
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,M,05/05/75,Married,US Citizen,IT/IS,Fully Meets,4.96,3
2,"Akinkuolie, Sarah",Production Technician II,MA,F,09/19/88,Married,US Citizen,Production,Fully Meets,3.02,3
3,"Alagbe,Trina",Production Technician I,MA,F,09/27/88,Married,US Citizen,Production,Fully Meets,4.84,5
4,"Anderson, Carol",Production Technician I,MA,F,09/08/89,Divorced,US Citizen,Production,Fully Meets,5.00,4

In [22]:
# Crear variables dummy para la columna categorica de Sex
dummy_sex= pd.get_dummies(df_rh1["Sex"], prefix="sex")

In [24]:
dummy_sex.head()

   sex_F  sex_M
0  False    True
1  False    True
2   True   False
3   True   False
4   True   False

In [26]:
# Eliminar la columna de "Sex" del DataFrame original para evitar redundancia
df_rh1 = df_rh1.drop(["Sex"], axis=1)

In [30]:
# Agrear columnas dummy al DataFrame original
df_rh2 = pd.concat([df_rh1,dummy_sex], axis=1)
df_rh2

,Employee_Name,Position,State,DOB,MaritalDesc,CitizenDesc,Department,PerformanceScore,EngagementSurvey,EmpSatisfaction,sex_F,sex_M
0,"Adinolfi, Wilson K",Production Technician I,MA,07/10/83,Single,US Citizen,Production,Exceeds,4.60,5,False,True
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,05/05/75,Married,US Citizen,IT/IS,Fully Meets,4.96,3,False,True
2,"Akinkuolie, Sarah",Production Technician II,MA,09/19/88,Married,US Citizen,Production,Fully Meets,3.02,3,True,False
3,"Alagbe,Trina",Production Technician I,MA,09/27/88,Married,US Citizen,Production,Fully Meets,4.84,5,True,False
4,"Anderson, Carol",Production Technician I,MA,09/08/89,Divorced,US Citizen,Production,Fully Meets,5.00,4,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",Production Technician II,MA,05/11/85,Single,US Citizen,Production,Fully Meets,4.07,4,False,True
307,"Ybarra, Catherine",Production Technician I,MA,05/04/82,Single,US Citizen,Production,PIP,3.20,2,True,False
308,"Zamora, Jennifer",CIO,MA,08/30/79,Single,US Citizen,IT/IS,Exceeds,4.60,5,True,False
309,"Zhou, Julia",Data Analyst,MA,02/24/79,Single,US Citizen,IT/IS,Fully Meets,5.00,3,True,False
310,"Zima, Colleen",Production Technician I,MA,08/17/78,Widowed,US Citizen,Production,Fully Meets,4.50,5,True,False

In [39]:
# Crear variables dummy para una columna en especifico
def createdummies(df,varname):
    #pd.get_dummies() de Pandas se utiliza para convertir variables categóricas 
    #en variables dummy o indicadores
    dummy = pd.get_dummies(df[varname], prefix= varname)
    # Eliminar la columna original para evitar redundancia
    df = df.drop(varname, axis=1)
    #Concatenar las columnas dummy con el dataframe original 
    df=pd.concat([df,dummy], axis=1)
    return df
createdummies(df_rh2, "MaritalDesc")

,Employee_Name,Position,State,DOB,CitizenDesc,Department,PerformanceScore,EngagementSurvey,EmpSatisfaction,sex_F,sex_M,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
0,"Adinolfi, Wilson K",Production Technician I,MA,07/10/83,US Citizen,Production,Exceeds,4.60,5,False,True,False,False,False,True,False
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,05/05/75,US Citizen,IT/IS,Fully Meets,4.96,3,False,True,False,True,False,False,False
2,"Akinkuolie, Sarah",Production Technician II,MA,09/19/88,US Citizen,Production,Fully Meets,3.02,3,True,False,False,True,False,False,False
3,"Alagbe,Trina",Production Technician I,MA,09/27/88,US Citizen,Production,Fully Meets,4.84,5,True,False,False,True,False,False,False
4,"Anderson, Carol",Production Technician I,MA,09/08/89,US Citizen,Production,Fully Meets,5.00,4,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",Production Technician II,MA,05/11/85,US Citizen,Production,Fully Meets,4.07,4,False,True,False,False,False,True,False
307,"Ybarra, Catherine",Production Technician I,MA,05/04/82,US Citizen,Production,PIP,3.20,2,True,False,False,False,False,True,False
308,"Zamora, Jennifer",CIO,MA,08/30/79,US Citizen,IT/IS,Exceeds,4.60,5,True,False,False,False,False,True,False
309,"Zhou, Julia",Data Analyst,MA,02/24/79,US Citizen,IT/IS,Fully Meets,5.00,3,True,False,False,False,False,True,False
310,"Zima, Colleen",Production Technician I,MA,08/17/78,US Citizen,Production,Fully Meets,4.50,5,True,False,False,False,False,False,True